version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management 
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management web UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Default RabbitMQ username
      RABBITMQ_DEFAULT_PASS: guest  # Default RabbitMQ password